# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
name: Flame
options:
  bundleIdPrefix: org.jerakeen
packages:
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift.git
    from: 6.5.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.0.1

targets:

  Utils:
    name: Utils
    type: library.static
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: "Utils"
        name: "Utils"
    dependencies:
      - package: RxSwift

  Views:
    name: Views
    type: library.static
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: "Views"
        name: "Views"
    dependencies:
      - target: Utils
      - package: RxSwift
      - package: RxSwift
        product: RxCocoa

  ServiceDiscovery:
    name: ServiceDiscovery
    type: library.static
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: "ServiceDiscovery"
        name: "ServiceDiscovery"
    dependencies:
      - package: RxSwift
      - target: Utils

  ServiceDiscoveryTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    transitivelyLinkDependencies: true
    sources:
      - ServiceDiscoveryTests
    dependencies:
      - target: ServiceDiscovery
    info:
      path: Test-Info.plist

  Flame:
    name: Flame
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    scheme:
      testTargets:
        - ServiceDiscoveryTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.jerakeen.flametouch
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        DEVELOPMENT_TEAM: 76AFK3W7M9
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: Flametouch dev (with multicast)
        PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]: Flametouch Mac Dev
      debug:
      release:
    sources:
      - path: "Flame"
      - path: "README.md"
        buildPhase: none
      - path: "CHANGELOG.md"
        buildPhase: none
      - path: "project.yml"
        buildPhase: none
      - path: ".swiftlint.yml"
        buildPhase: none
    dependencies:
      - package: SnapKit
      - package: RxSwift
      - package: RxSwift
        product: RxCocoa
      - target: ServiceDiscovery
      - target: Utils
      - target: Views

    info:
      path: Info.plist
      properties:
        NSLocalNetworkUsageDescription: Flame lists the local network services to let you browse them
        LSApplicationCategoryType: public.app-category.developer-tools
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: LaunchIcon
        # I fucked up and got these backwards once and now every version must be >80
        CFBundleShortVersionString: "103.1.0"
        CFBundleVersion: "90"
        ITSAppUsesNonExemptEncryption: false
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Main
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
              - UISceneConfigurationName: About
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).AboutSceneDelegate
    entitlements:
      path: Flame.entitlements
      properties:
        com.apple.developer.networking.multicast: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
        com.apple.security.app-sandbox: true
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
