# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "a013db4d-c350-4f4a-a14e-2b7086017297"

default_platform :ios

xcversion(version: "9")

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do

    appicon(
        appicon_image_file: 'Image Resources/AppIcon.png',
        appicon_devices: [:ipad, :iphone, :ios_marketing],
        appicon_path: 'flametouch/Assets.xcassets',
    )

    # https://docs.fastlane.tools/getting-started/ios/beta-deployment/#best-practices
    # rebuilds profile if the number of devices has changed
    register_devices(devices_file: "fastlane/devices.txt")
    match(type: "adhoc", force_for_new_devices: true)

    gym

    changelog_from_git_commits

    crashlytics(
        groups: ["Testers"],
        notifications: true,
    )

    increment_build_number
end

lane :testflight do
    match(type: "appstore")
    gym
    testflight
end

lane :dsyms do
    download_dsyms
    upload_symbols_to_crashlytics
end


