fastlane_version "2.99.0"

default_platform :ios
#xcversion(version: "9")

lane :beta do

    # https://docs.fastlane.tools/getting-started/ios/beta-deployment/#best-practices
    # rebuilds profile if the number of devices has changed
    register_devices(devices_file: "fastlane/devices.txt")
    match(type: "adhoc", force_for_new_devices: true, app_identifier: "org.jerakeen.flame.debug")

    gym(configuration: "Debug")

    changelog_from_git_commits

    hockey(
        api_token: "0cbda07021a541d7af383b3aac7737d5",
    )

    increment_build_number

end

lane :release do
    match(type: "appstore")
    gym
    testflight
    increment_build_number
end

lane :dsyms do
    download_dsyms
    upload_symbols_to_crashlytics(
        :binary_path => "./Carthage/Build/iOS/Crashlytics.framework/uploadDSYM"
    )
end

lane :bump do
    increment_build_number
end

lane :icon do
    appicon(
        appicon_image_file: 'Image Resources/AppIcon.png',
        appicon_devices: [:ipad, :iphone, :ios_marketing],
        appicon_path: 'flametouch/Assets.xcassets',
    )
end
